import React from 'react';

export default function TermsAndConditionsPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl prose prose-slate dark:prose-invert">
      <h1 className="text-3xl font-bold mb-6">KK’s WAR ROOM – Terms & Conditions</h1>

      <h2 className="text-2xl font-semibold mt-8 mb-4">A. Before Entering the WAR ROOM (Participant Agreement)</h2>

      <div className="space-y-4">
        <div>
          <h3 className="text-lg font-medium">1. Nature of the Experience</h3>
          <p>KK’s WAR ROOM is a high-pressure, simulation-based experience designed to evaluate decision-making, problem-solving, and entrepreneurial thinking under time and situational constraints. This is not a standardized psychometric, academic, or clinical assessment.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">2. Voluntary Participation</h3>
          <p>Participation is voluntary. You may withdraw at any time; however, incomplete participation may affect your report.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">3. Developmental Purpose Only</h3>
          <p>This experience is intended solely for learning, reflection, and development. It is not a measure of intelligence, personality, mental health, or professional capability.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">4. Observation, Recording & Data Collection</h3>
          <p>During the session:</p>
          <ul className="list-disc pl-5">
            <li>Your responses, decisions, and interactions will be observed and documented.</li>
            <li>Sessions may be audio/video recorded for internal review and program improvement.</li>
            <li>Recordings will remain confidential and will not be publicly shared without explicit consent.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">5. Report Sharing & Visibility</h3>
          <p>If your participation is part of a school, college, or corporate program:</p>
          <ul className="list-disc pl-5">
            <li>Your report may be shared with authorized stakeholders (such as faculty, sponsors, or management).</li>
            <li>These stakeholders may have access to your participation details, decision-making approach, and performance within the simulation.</li>
          </ul>
          <p><strong>Important:</strong> Such sharing is strictly for learning and development purposes only. KK’s WAR ROOM does not authorize or recommend the use of this report for formal grading, hiring, promotion, or performance evaluation.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">6. Data Protection & Privacy</h3>
          <p>Personal and assessment data will be used only for program delivery, reporting, and improvement. Data will not be sold or shared with unauthorized third parties. Access is restricted to authorized personnel and relevant stakeholders (where applicable). Reasonable measures will be taken to protect stored data. You may request access to or deletion of your data, subject to legal and operational requirements.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">7. Use of AI in the Experience (No Human Review)</h3>
          <p>KK’s WAR ROOM uses AI-driven systems for:</p>
          <ul className="list-disc pl-5">
            <li>Scenario generation</li>
            <li>Response analysis</li>
            <li>Report creation</li>
          </ul>
          <p>All outputs are fully generated by automated systems without human review.</p>
          <p><strong>Important Clarifications:</strong> Outputs are algorithmic interpretations based on participant inputs and predefined frameworks. They may contain errors, omissions, biases, or inaccuracies. Insights are indicative and exploratory, not verified conclusions.</p>
          <p>By participating, you acknowledge that:</p>
          <ul className="list-disc pl-5">
            <li>The outputs are not guaranteed to be accurate, complete, or reliable.</li>
            <li>They should be used only for self-reflection and development purposes.</li>
            <li>You will not rely on these outputs as the sole basis for academic, professional, or personal decisions.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">8. Confidentiality</h3>
          <p>Participants agree not to disclose or share:</p>
          <ul className="list-disc pl-5">
            <li>Other participants’ responses or behaviors.</li>
            <li>Simulation content, discussions, or scenarios.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">9. Intellectual Property</h3>
          <p>All materials, frameworks, scenarios, and methodologies are proprietary. Recording, copying, distributing, or recreating the experience without written permission is prohibited.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">10. Code of Conduct</h3>
          <p>Participants must engage respectfully and professionally. KK’s WAR ROOM reserves the right to remove participants for inappropriate or disruptive behavior.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">11. Emotional & Psychological Acknowledgment</h3>
          <p>Participants acknowledge that:</p>
          <ul className="list-disc pl-5">
            <li>The simulation may involve stress, pressure, or discomfort.</li>
            <li>Participation is at their own discretion.</li>
            <li>They may pause or withdraw at any time.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">12. No Professional Advice</h3>
          <p>This experience does not constitute psychological, medical, legal, financial, or career advice.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">13. Limitation of Liability</h3>
          <p>To the maximum extent permitted by law: KK’s WAR ROOM and its facilitators shall not be liable for any direct, indirect, incidental, or consequential loss, damage, or impact arising from participation in the simulation or use of its outputs. All actions taken based on the insights provided are the sole responsibility of the participant or organization.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">14. Indemnification</h3>
          <p>Participants and sponsoring organizations agree to indemnify and hold harmless KK’s WAR ROOM from any claims, damages, or liabilities arising from:</p>
          <ul className="list-disc pl-5">
            <li>Participation in the program.</li>
            <li>Use or misuse of outputs or reports.</li>
            <li>Decisions made based on the insights provided.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">15. Minor Participation (if applicable)</h3>
          <ul className="list-disc pl-5">
            <li>Participants under the age of 18 must have consent from a parent or legal guardian.</li>
            <li>The guardian agrees to these terms on behalf of the participant.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">16. Governing Law</h3>
          <p>These terms shall be governed by the laws of the State of Florida, United States.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">17. Consent Acknowledgment</h3>
          <p>By participating, you confirm that:</p>
          <ul className="list-disc pl-5">
            <li>You have read and understood these terms.</li>
            <li>You voluntarily agree to participate.</li>
            <li>You consent to data usage and report sharing as described above.</li>
          </ul>
        </div>
      </div>

      <h2 className="text-2xl font-semibold mt-12 mb-4">B. Terms and Conditions: WAR ROOM Evaluation Report</h2>

      <div className="space-y-4">
        <div>
          <h3 className="text-lg font-medium">1. Nature of the Report</h3>
          <p>This report reflects observed behavioral tendencies within a specific simulation context. It is not a standardized, scientific, or diagnostic assessment.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">2. Developmental Use Only</h3>
          <p>This report is intended solely for learning and development purposes. It must not be used as the sole basis for:</p>
          <ul className="list-disc pl-5">
            <li>Academic grading</li>
            <li>Hiring decisions</li>
            <li>Promotions or role assignments</li>
            <li>Performance evaluations</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">3. Context-Specific Interpretation</h3>
          <p>Results are influenced by:</p>
          <ul className="list-disc pl-5">
            <li>Scenario design</li>
            <li>Time pressure</li>
            <li>Available information</li>
          </ul>
          <p>Behavior may differ significantly in real-world environments.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">4. Indicative Insights Only</h3>
          <p>The report highlights tendencies, not fixed abilities. It does not represent the participant’s full capability or potential.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">5. AI-Generated Output (No Human Validation)</h3>
          <p>This report is generated entirely through AI-based systems without human validation.</p>
          <ul className="list-disc pl-5">
            <li>Insights are interpretative and non-verified.</li>
            <li>Outputs may include biases, inaccuracies, or incomplete analysis.</li>
            <li>The report should not be treated as factual, diagnostic, or authoritative.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">6. Subjectivity of Evaluation</h3>
          <p>Results are based on algorithmic interpretation and predefined frameworks. They are not fully objective or comprehensive.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">7. Organizational Use Disclaimer</h3>
          <p>If shared with an institution or employer:</p>
          <ul className="list-disc pl-5">
            <li>The report is intended only for development discussions.</li>
            <li>It must be combined with other evaluation methods and professional judgment.</li>
            <li>KK’s WAR ROOM is not responsible for decisions made by third parties using this report.</li>
          </ul>
        </div>

        <div>
          <h3 className="text-lg font-medium">8. Limitation of Liability</h3>
          <p>KK’s WAR ROOM shall not be liable for any decisions, actions, or outcomes arising from the use or interpretation of this report.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">9. Confidentiality & Use</h3>
          <p>This report is confidential and intended only for:</p>
          <ul className="list-disc pl-5">
            <li>The participant</li>
            <li>Authorized stakeholders (if applicable)</li>
          </ul>
          <p>Unauthorized sharing, misrepresentation, or commercial use is prohibited.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">10. Intellectual Property</h3>
          <p>All report formats, frameworks, and methodologies are proprietary. Reproduction or distribution without permission is not allowed.</p>
        </div>

        <div>
          <h3 className="text-lg font-medium">11. Final Note</h3>
          <p>This report is a reflection of how you responded under pressure. It is not a definition of who you are or what you can become.</p>
        </div>
      </div>
    </div>
  );
}
